protected/controllers/UserController.php
<?php

class UserController extends Controller {
    const PAGE_SIZE = 10;

    /**
     * @var string specifies the default action
     */
    public $defaultAction='admin';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_user;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',  // all users
                'actions'=>array('create', 'confirm', 'welcome',
                				'reset', 'resetThanks',
                                'sendActivationEmail','emailWelcome','emailReset'),
                'users'=>array('*'),
            ),
            array('allow', # logged in users
                    'actions'=>array('welcome', 'activationNeeded', 'changePassword','view_profile','edit_profile'),
                    'users'=>array('@'),
                ),
            array('allow', # admins
                'actions'=>array('list', 'show', 'delete','admin','update','view','newsletter'),
                'roles'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Shows a particular user.
     */
    public function actionShow() {
        #if (Yii::app()->user->checkAccess('showUser')) {
        #}
        $this->render('show',array('user'=>$this->loadUser()));
    }

    # Create new account
    public function actionCreate() {
        $this->layout='new_main';
        $user = new User;
        $user->newsletter=false;
        $this->performAjaxValidation($user);
        if (isset($_POST['User'])) {
            //$user->attributes = $_POST['User'];

            $attrs = $_POST['User'];
            $user->attributes=$attrs;
            $user->email = strtolower(trim($attrs['email']));
            $user->username = $user->email;
            $user->first_name = trim($attrs['first_name']);
            $user->last_name = trim($attrs['last_name']);
            $user->password = $attrs['password'];
            $user->password_repeat = $attrs['password_repeat'];
            $user->first_name=$attrs['first_name'];
            $user->last_name=$attrs['last_name'];
            $user->affiliation = $attrs['affiliation'];
            $user->preferred_link = $attrs['preferred_link'];

            if (!Yii::app()->user->checkAccess('admin')) {
                $user->role = 'user'; // avoid send POST hacking
            }
            $user->newsletter=$attrs['newsletter'];
            $user->previous_newsletter_state = !$user->newsletter;

            if ($user->validate('insert')) {
                $user->encryptPassword();

                if ($user->save(false)) {
                    $this->sendActivationEmail($user);
                    if($user->newsletter)
                        Yii::app()->newsletter->addToMailing($user->email);

                    $this->redirect(array('welcome', 'id'=>$user->id));
                }
                else {
                    Yii::log(__FUNCTION__."> create failed", 'warning');
                }
            }
            else {
                Yii::log(__FUNCTION__."> validation failed", 'warning');
            }
        }
        $this->render('create', array('model'=>$user)) ;
    }

    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax']==='user-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    /**
     * Updates a particular user.
     * If update is successful, the browser will be redirected to the 'show' page.
     */
    public function actionUpdate() {
        $user = $this->loadUser();
        $this->performAjaxValidation($user);
        #if (!Yii::app()->user->checkAccess('updateOwnUser', array('user'=>$user))) {
        #    Yii::log(__FUNCTION__."> Unauthorized", 'debug');
        #    throw new CHttpException(403, 'You are not authorized to perform this action.');
        #}




        if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'] ;
            $attrs = $_POST['User'];

            $password = $user->password_new = $attrs['password'];
            $user->password_repeat = $attrs['password_repeat'];

            if (!Yii::app()->user->checkAccess('admin')) {
                $user->role = 'user';
            }

            if ($user->validate('update')) {
                if ($password != '') {
                    $user->encryptPassword();
                }

                if ($user->save(false)) {

                    Yii::app()->user->setFlash('notice', 'Updated');
                    $this->redirect(array('user/show/id/'.$user->id));
                }
                else {
                    Yii::log(__FUNCTION__."> Update failed", 'warning');
                }

            }
            else {
                Yii::log(__FUNCTION__."> validation failed", 'warning');
            }
        }
        $user->password = $user->password_repeat = '';
        $this->render('update', array('model'=>$user));

    }

    /**
     * Deletes a particular user.
     * If deletion is successful, the browser will be redirected to the 'list' page.
     */
    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            # we only allow deletion via POST request
            $user =User::model()->findbyPk($_GET['id']) ;
            $auth = Yii::app()->authManager;
            $auth->revoke($user->getRole(), $user->email);
            //$user->delete();

            $user->is_activated = False;
            if ($user->save(False))
                $this->redirect(array('admin'));
            else{
                Yii::log("Saving user error" . print_r($user->getErrors(), true), 'error');
            }

        }
        else {
            throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');
        }
    }

    /**
     * Lists all users.
     */
    public function actionList() {
        $criteria = new CDbCriteria;

        $pages = new CPagination(User::model()->count($criteria));
        $pages->pageSize = self::PAGE_SIZE;
        $pages->applyLimit($criteria);

        $sort = new CSort('User');
        $sort->applyOrder($criteria);

        $userList = User::model()->findAll($criteria);

        $this->render('list',array(
            'userList'=>$userList,
            'pages'=>$pages,
            'sort'=>$sort,
        ));
    }

    /**
     * Manages all users.
     */
    public function actionAdmin() {
        $model=new User('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['User']))
            $model->setAttributes($_GET['User']);

        $this->render('admin',array(
            'model'=>$model,
        ));
    }
    
    public function actionNewsletter(){
        
     $result = User::model()->findAllBySql("select email,first_name, last_name, affiliation from gigadb_user where newsletter=true order by id;");
     
                 
     $this->renderPartial('newsletter',array(
            'models'=>$result,
        ));
       
        
    }

    # Confirm email works
	public function actionConfirm() {
		$key = $_GET['key'] ;
		User::model()->updateAll(array('is_activated'=>1),'id=:unique_id', array(':unique_id'=>$key));

        $user = User::model()->findByAttributes(array('id' => $key));
        if ($user->is_activated) {
            $this->sendNotificationEmail($user);
        }

		$this->render('confirm', array('user'=>$user));
	}

    public function actionWelcome() {
        $this->render('welcome', array('user'=>$this->loadUser())) ;
    }

    public function actionActivationNeeded() {
        $this->render('activationNeeded', array('user'=>$this->loadUser())) ;
    }

    # Look up user and reset password
    public function actionReset() {
        $this->layout='new_main';
        $user = new User;
        $user->newsletter=false;
    	$user->email='';
        $user->terms=false;
        //$this->render('reset',array('user'=>$this->loadUser())) ;
        if (isset($_POST['User'])) {
        
            $attrs = $_POST['User'];
            $user = User::model()->findByAttributes(array('email' => trim($attrs['email'])));
            if ($user !== null) {
                Yii::log(__FUNCTION__."> reset found user $user->email", 'debug');
                $user->password = $user->generatePassword(8);
                $user->is_activated=true;
                $user->terms= $attrs['terms'];
                $user->newsletter= $attrs['newsletter'];
                $user->encryptPassword();

                if ($user->save(false)) {
                    Yii::log("Update password and prepare to send email");
                    $this->sendPasswordEmail($user);
                }
                else {
                    Yii::log(__FUNCTION__."> Error: could not save new user password", 'error');
                }
            }
            else {
                Yii::log(__FUNCTION__."> User account not found for user ", 'error');
            }
            $this->redirect(array('user/resetThanks'));
        }
        $this->render('reset', array('model'=>$user));
    }

    public function actionResetThanks() {
        $this->render('resetThanks');
    }

    # Reset password and send it to user in email
    public function actionLostPass() {
        $user = $this->loadUser();
        if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'];
            $user->password = $user->generatePassword(8);
            $user->encryptPassword();

protected/views/user/_form.php
 <div class="content">

<?php
    foreach(Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
    }
?>
<?php
      $user_command = UserCommand::model()->findByAttributes(array("requester_id" => $model->id, "status" => "pending")) ;
      $linked_author = Author::findAttachedAuthorByUserId($model->id) ;

?>

<div class="clear"></div>
<?php
      if ( null != $user_command ) {
      	$claimed_author = Author::model()->findByPk($user_command->actionable_id);
      	$message = "This user has a pending claim on author ". $claimed_author->getDisplayName() ;
      	$validate_link = CHtml::link('Validate', 
                                    array('AdminUserCommand/validate', 'id' => $user_command->id),
                                    array('class' => 'btn'));
      	$reject_link = CHtml::link('Reject', 
                                    array('AdminUserCommand/reject', 'id' => $user_command->id),
                                    array('class' => 'btn'));
      	$author_link = CHtml::link('Author info', 
                                    array('AdminAuthor/view', 'id' => $user_command->actionable_id),
                                    array('class' => 'btn'));
?>
	    <div class="alert alert-info">
	    	<? echo $message ?>
	    	<div class="btn-toolbar">
			    <? echo $validate_link ?>
			    <? echo $reject_link ?>
			    <? echo $author_link ?>
			</div>
		</div>

<?php
      }
      else if ( null ==  $linked_author) {
          echo CHtml::link('Link this user to an author', 
                                    array('adminAuthor/prepareUserLink', 'user_id'=>$model->id),
                                    array('class' => 'btn')); 
      }else {
      	$unlink_link =  CHtml::link('Unlink author', 
                                    array('AdminAuthor/unlinkUser', 'id' => $linked_author->id, 'user_id'=>$model->id),
                                    array('class' => 'btn'));
?>
        <div class="alert">This user is linked to author: <? echo $linked_author->getDisplayName() ?> (<? echo $linked_author->id ?>)
			<div class="btn-toolbar">
			    <? echo $unlink_link ?>
			</div>
        </div>
<?php
      }
?>
 	
        <div class="container">
              <section class="page-title-section">
                <div class="page-title">
                    <ol class="breadcrumb pull-right">
                        <li><a href="/">Home</a></li>
                        <li class="active">Personal details</li>
                    </ol>
                    <h4>Registration</h4>
                </div>
            </section>
        <div class="subsection" style="margin-bottom: 130px;">
	
		<div class="clear"></div>
		<?php if ($model->isNewRecord) {?>
		<p><?=Yii::t('app' , 'GigaScience appreciates your interest in the GigaDB project. With a GigaDB account, you can submit new datasets to the database. Also, GigaDB can automatically notify you of new content which matches your interests. Please fill out the following information and register to enjoy the benefits of GigaDB membership!')?></p>
<?}
		?>
		<?php $text = $this->captchaGenerator(); ?>
		<p>Fields with <span class="symbol">*</span> are required.</p>
		<div class="create-div">
			<? $form=$this->beginWidget('CActiveForm', array(
				'id'=>'user-form',
				'enableAjaxValidation'=>false,
				'htmlOptions'=>array('class'=>'form-horizontal')
			)) ?>
				 <div class="form-group">
					<?= $form->labelEx($model,'email', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= $form->textField($model,'email',array('class'=>'form-control')) ?>
						<font color="red"><?= $form->error($model,'email') ?></font>
					</div>
				</div>

				<div class="form-group">
					<?= $form->labelEx($model,'first_name', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= $form->textField($model,'first_name',array('class'=>'form-control')) ?>
						<font color="red"><?= $form->error($model,'first_name') ?></font>
					</div>
				</div>

				<div class="form-group">
					<?= $form->labelEx($model,'last_name', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= $form->textField($model,'last_name',array('class'=>'form-control')) ?>
						<font color="red"><?= $form->error($model,'last_name') ?></font>
					</div>
				</div>

				<div class="form-group">
					<?= $form->labelEx($model,'password', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= $form->passwordField($model,'password',array('class'=>'form-control')) ?>
						 <font color="red"><?= $form->error($model,'password') ?></font>
					</div>
				</div>

				<div class="form-group">
					<?= $form->labelEx($model,'password_repeat', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= $form->passwordField($model,'password_repeat',array('class'=>'form-control')) ?>
						<font color="red"><?= $form->error($model,'password_repeat') ?></font>
					</div>
				</div>
				<? if (Yii::app()->user->checkAccess('admin')) { ?>
					<div class="form-group">
						<?= $form->labelEx($model,'role', array('class'=>'col-xs-3 control-label')) ?>
						<div class="col-xs-9">
							<?= $form->dropDownList($model,'role',array('user'=>'user','admin'=> 'admin','class'=>'dropdown-menu')) ?>
							 <font color="red"><?= $form->error($model,'role') ?></font>
						</div>
					</div>
				<? } ?>
				<div class="form-group">
					<?= $form->labelEx($model,'affiliation', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= $form->textField($model,'affiliation',array('class'=>'form-control')) ?>
						<font color="red"><?= $form->error($model,'affiliation') ?></font>
					</div>
				</div>
				<div class="form-group">
					<?= $form->labelEx($model,'preferred_link', array('class'=>'col-xs-3 control-label')) ?>
					<div class="col-xs-9">
						<?= CHtml::activeDropDownList($model,'preferred_link', User::$linkouts, array()) ?>
						<font color="red"><?= $form->error($model,'preferred_link') ?></font>
					</div>
				</div>
                                <div class="form-group">
                                    <label class="col-xs-3 control-label"><?=Yii::t('app' , 'Mailing list')?></label>
                                   
				    <div class="col-xs-9">				    	
                                         <?php echo $form->checkbox($model,'newsletter'); ?>
				    </div>
                                    <div class="col-xs-9">
                                        <p>Please tick here to join the GigaDB mailing list to receive news, updates and quarterly newsletters about GigaDB</p>   
                                    </div>
                                 </div>
                                <div class="form-group">
                                    <?= $form->labelEx($model,'terms', array('class'=>'col-xs-3 control-label')) ?>              
				    <div class="col-xs-9">				    	
                                         <?php echo $form->checkbox($model,'terms'); ?>
                                         <font color="red"><?= $form->error($model,'terms') ?></font>
				    </div>
                                    <div class="col-xs-9">
                                     <p>Please tick here to confirm you have read and understood our <a href="/site/term#policies">Terms of use</a> and <a href="/site/term#privacy">Privacy Policy</a></p>
                                    </div>
                                 </div>
                                


			<? if ($model->isNewRecord) { ?>
			<div class="form-group">		
					<?php echo $form->labelEx($model,'verifyCode', array('class'=>'col-xs-3 control-label')); ?>		
			        <div class="col-xs-9">				
						<div style="width:100%">	
							<img style="width:200px;" src="/images/tempcaptcha/<?php echo $text; ?>.png">	
						</div>
                                    <br>
                                    <br>
						<?php echo $form->textField($model,'verifyCode',array('class'=>'form-control')); ?>	
						<div class="hint">Please enter the letters as they are shown in the image above.
						<br/>Letters are case-sensitive.</div>
						<?php echo $form->error($model, 'verifyCode'); ?>					
						</div>		
			    </div>
			<? } ?>
                        <hr>
                            <div class="button-div">
                                <?= CHtml::submitButton($model->isNewRecord ? Yii::t('app' , 'Register') : 'Save', array('class'=>'btn background-btn')) ?>
                            </div>
                        <? $this->endWidget() ?>
		</div><!--well-->
		


	<?php 
		$path = "images/tempcaptcha/".$text.".png";
		$files = glob('images/tempcaptcha/*');
		foreach($files as $file){ 
		  if (is_file($file))
		  	if ($file != $path)
		  		 unlink($file); 
		}
	?>	
	</div><!--span8-->
    </div><!-- user-form -->
</div>

protected/views/user/activationNeeded.php
<?php $this->pageTitle = Yii::app()->name . ' - Welcome' ?>

<h2><?=Yii::t('app' , 'Account Activation')?></h2>
<div class="clear"></div>

<div class="yiiForm">
<p><?=Yii::t('app' , 'An account activation email has been emailed to your email address.')?></p>
<p><?=Yii::t('app' , 'If you don\'t receive the email within a few minutes, please check your spam filters.')?> <br/>
<?=Yii::t('app' , 'Click')?> <?= CHtml::link(Yii::t('app' ,"here"), array("user/sendActivationEmail", 'id'=>$user->id)) ?> <?=Yii::t('app' , 'to resend the email')?>
<?=Yii::t('app' , 'or') ?> <?= CHtml::link(Yii::t('app' ,"contact us"), "mailto:" . Yii::app()->params['support_email']) ?>&nbsp;
<?=Yii::t('app' , 'and we will get it sorted.')?>
</p>
</div><!-- yiiForm -->

protected/views/user/admin.php
<h2>Manage Users</h2>
<div class="clear"></div>
<p>
To list certain news items that you are looking for, you may search via keyword or value. Type your keyword or value into their respective boxes under the column headers and press the enter key. You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php $this->beginWidget('zii.widgets.jui.CJuiDialog', array(
  'id'=>'controls',
  // additional javascript options for the dialog plugin
  'options'=>array(
    'title'=>'Managing User',
    'autoOpen'=>false,
    'modal'=>true,
  ),
));

?>

<h3>Basic Operations</h3>
<a href="#" class="btn btn-active" title="view" onclick="goto_userview();">View</a>
<a href="#" class="btn btn-active" title="update" onclick="goto_userupdate();">Update</a>
<a href="#" class="btn btn-active delete" title="delete" onclick="goto_userdelete();">Delete</a>

<h3>Advanced Operations</h3>
<a href="#" class="btn btn-active delete" title="link" onclick="goto_userlinkauthor();">Link this user to an author</a>


<div id="status"></div>

<?

$this->endWidget('zii.widgets.jui.CJuiDialog');

?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
  'id'=>'news-grid',
  'dataProvider'=>$model->search(),
  'filter'=>$model, // turn on/off filtering
  'itemsCssClass'=>'table table-bordered',
  'selectionChanged'=>"function(id){open_controls($.fn.yiiGridView.getSelection(id));}",
  'columns'=>array(
    'id',
    'email',
    'first_name',
    'last_name',
    'role',
    'affiliation',
    'facebook_id',
    'twitter_id',
    'linkedin_id',
    'google_id',
    'username',  
    array(
        'name' => 'is_activated',
        'value' => '($data->is_activated) ? "Yes" : "No"'
        ),
    array(
      'name'=>'newsletter',
      'value'=>'$data->renderNewsletter()',
      ),
    array(
      'class'=>'CButtonColumn',

    ),
  ),
)); ?>

<script>
function open_controls(user_id) {
    $("#controls").data('user_id', user_id);
    $("#controls").dialog( "option", "title", "Manage User Id: " + user_id);
    $("#controls").dialog("open"); 
    return false;
}

function goto_userview() {
<?
  echo 'var userview_url = "'.Yii::app()->urlManager->createUrl('user/view',array('id'=>'')).'";'
?>
  var user_id = $("#controls").data('user_id');
  window.location= userview_url + "/" + user_id; 
}

function goto_userview() {
<?
  echo 'var base_url = "'.Yii::app()->urlManager->createUrl('user/view',array('id'=>'')).'";'
?>
  var user_id = $("#controls").data('user_id');
  window.location= userview_url + "/" + user_id; 
}

function goto_userview() {
<?
  echo 'var base_url = "'.Yii::app()->urlManager->createUrl('user/view',array('id'=>'')).'";'
?>
  var user_id = $("#controls").data('user_id');
  window.location= base_url + "/" + user_id; 
}

function goto_userupdate() {
<?
  echo 'var base_url = "'.Yii::app()->urlManager->createUrl('user/update',array('id'=>'')).'";'
?>
  var user_id = $("#controls").data('user_id');
  window.location= base_url + "/" + user_id; 
}

function goto_userdelete() {
<?
  echo 'var base_url = "'.Yii::app()->urlManager->createUrl('user/delete',array('id'=>'')).'";'
?>
  var user_id = $("#controls").data('user_id');
  //window.location= base_url + "/" + user_id; 
  $.ajax({
    url:base_url + "/" + user_id,
    type:'POST',
    success:function(data){
        $("#status").addClass("alert alert-success")
          .append("user successfully deactivated.")
          .append("Refresh the page to see the changes.");
    },
  });
}

function goto_userlinkauthor() {
<?
  echo 'var base_url = "'.Yii::app()->urlManager->createUrl('adminAuthor/prepareUserLink',array('user_id'=>'')).'";'
?>
  var user_id = $("#controls").data('user_id');
  window.location= base_url + "/" + user_id; 
}
</script>

protected/views/user/authoredDatasets.php
<section>
    <table class="table table-bordered" id="list">
        <thead>
            <tr>
                <th>
                    <?= Yii::t('app', 'DOI') ?>
                </th>
                <th>
                    <?= Yii::t('app', 'Title') ?>
                </th>
                <th>
                    <?= Yii::t('app', 'Dataset Type') ?>
                </th>
                <th>
                    <?= Yii::t('app', 'Status') ?>
                </th>
                <th>
                    <?= Yii::t('app', 'Publication Date') ?>
                </th>
                <th>
                    <?= Yii::t('app', 'Modification Date') ?>
                </th>
                <th>
                    <?= Yii::t('app','File Count') ?>
                </th>
            </tr>
        </thead>
        <?php $data = $authoredDatasets; ?>
        <?php
        for ($i = 0; $i < count($authoredDatasets); $i++) {
            $class = $i % 2 == 0 ? 'even' : 'odd';
            if(isset($selected) && $data[$i]->id==$selected) {
                $class = 'submit-selected';
            }
            ?>
            <tr class="<?php echo $class; ?>" id="js-dataset-row-<?=$data[$i]->id?>">
                <?
                $upload_status = $data[$i]->upload_status;

                if ( $upload_status != 'Published' && $upload_status!='Private' ) { ?>
                    <td class="content-popup" data-content="<? echo CHtml::encode($data[$i]->description); ?>">
                        unknown
                    </td>
                    <? } else { ?>
                        <td class="content-popup" data-content="<? echo CHtml::encode($data[$i]->description); ?>">
                            <? echo CHtml::link("10.5524/" . $data[$i]->identifier, "/dataset/" . $data[$i]->identifier, array('target' => '_blank')); ?>
                        </td>
                        <? } ?>
                            <td class="left content-popup" data-content="<? echo CHtml::encode($data[$i]->description); ?>">
                                <? echo $data[$i]->title; ?>
                            </td>
                            <td>
                                <? foreach ($data[$i]->datasetTypes as $type) { ?>
                                    <?= $type->name ?>
                                        <? } ?>
                            </td>
                            <td>
                                <?= CHtml::encode($data[$i]->upload_status) ?>
                            </td>
                            <td>
                                <? echo CHtml::encode($data[$i]->publication_date); ?>
                            </td>
                            <td>
                                <? echo CHtml::encode($data[$i]->modification_date); ?>
                            </td>
                            <td>
                                <? echo count($data[$i]->files); ?>
                            </td>
            </tr>
            <? } ?>
    </table>
</section>

protected/views/user/changePassword.php
<h2><?= Yii::t('app', 'Change Password') ?></h2>
<div class="clear"></div>
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-default profile-panel">
                <div class="panel-body">

                    <?php
                    $form = $this->beginWidget('CActiveForm', array(
                        'id' => 'ChangePassword-form',
                        'enableAjaxValidation' => false,
                        'htmlOptions' => array('class' => 'form-horizontal'),
                    ));
                    ?>

                        <?= isset($error) && $error ? '<div class="row">' . $error . '</div>' : '' ?>

                    <div class="form-group">
                            <?php echo $form->labelEx($model, 'password', array('class' => 'col-xs-5 control-label')); ?>
                        <div class="col-xs-5">
<?php echo $form->passwordField($model, 'password', array('size' => 60, 'maxlength' => 128, 'class' => 'form-control', 'value' => "")); ?>
<?php echo $form->error($model, 'password'); ?>
                        </div>
                    </div>


                    <div class="form-group">
                            <?php echo $form->labelEx($model, 'confirmPassword', array('class' => 'col-xs-5 control-label')); ?>
                        <div class="col-xs-5">
<?php echo $form->passwordField($model, 'confirmPassword', array('size' => 60, 'maxlength' => 128, 'class' => 'form-control')); ?>
<?php echo $form->error($model, 'confirmPassword'); ?>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-xs-5 control-label"><?= Yii::t('app', 'Mailing list') ?></label>

                        <div class="col-xs-5">				    	
<?php echo $form->checkbox($model, 'newsletter'); ?>
                        </div>
                        <div class="col-xs-5">
                            <p>Please tick here to join the GigaDB mailing list to receive news, updates and quarterly newsletters about GigaDB</p>   
                        </div>
                    </div>
                    <div class="form-group">
                            <?= $form->labelEx($model, 'terms', array('class' => 'col-xs-5 control-label')) ?>              
                        <div class="col-xs-5">				    	
<?php echo $form->checkbox($model, 'terms'); ?>
                            <br>
                            <font color="red"><?= $form->error($model, 'terms') ?></font>
                            <p>Please tick here to confirm you have read and understood our <a href="/site/term#policies">Terms of use</a> and <a href="/site/term#privacy">Privacy Policy</a></p>
                        </div>
                    
                        
                    </div>                     


                    <div class="pull-right">
                        <a href="/user/view_profile" class="btn background-btn"><?= Yii::t('app', 'Cancel') ?></a>
                    <?php echo CHtml::submitButton(Yii::t('app', 'Save'), array('class' => 'btn background-btn')); ?>
                    </div>
                    <div class="clear"></div>
<?php $this->endWidget(); ?>

                </div><!--span8-->
            </div>
        </div>
    </div>
</div><!-- user-form -->
<br>
<br>

protected/views/user/confirm.php
<? if ($user->is_activated) { ?>
<h3>Your account has been activated</h3>

<p><?= CHtml::link("Log in", array('site/login')) ?> to configure your account.</p>
<? } else { ?>
<h3>Account Pending</h3>

You are now registered. We will contact you shortly. Feel free to
or <?= CHtml::link("contact us", "mailto:" . Yii::app()->params['support_email']) ?>&nbsp;
if you prefer.</p>
<? } ?>

protected/views/user/list.php
<h2>User List</h2>

<div class="actionBar">
[<?= CHtml::link('New User',array('create')); ?>]
[<?= CHtml::link('Manage User',array('admin')); ?>]
</div>

<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

<div class="item">
<?php foreach($userList as $n=>$model): ?>
<?= CHtml::encode($model->id); ?>:
<?= CHtml::link($model->email,array('show', 'id'=>$model->id)); ?>
 (<?= CHtml::encode($model->email); ?>)
 (<strong><?= CHtml::encode($model->getRole()); ?></strong>)
<br/>

<?php endforeach; ?>
</div>
<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

protected/views/user/newsletter.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
echo "Email"."||"."First_name"."||"."Last_name"."||"."Affiliation";
?>
<br>
   <? 
   
foreach ($models as $model) {

    echo $model->email."||".$model->first_name."||".$model->last_name."||".$model->affiliation;
    ?>
<br>
   <? 
}
?>